[2024-11-14T17:03:43.910+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T17:03:43.936+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Stock_DAG_ELT_dbt.dbt_run manual__2024-11-14T17:03:43.321840+00:00 [queued]>
[2024-11-14T17:03:43.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Stock_DAG_ELT_dbt.dbt_run manual__2024-11-14T17:03:43.321840+00:00 [queued]>
[2024-11-14T17:03:43.943+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T17:03:43.955+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-14 17:03:43.321840+00:00
[2024-11-14T17:03:43.961+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Stock_DAG_ELT_dbt', 'dbt_run', 'manual__2024-11-14T17:03:43.321840+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/Stock_DAG_ELT.py', '--cfg-path', '/tmp/tmp1u121auv']
[2024-11-14T17:03:43.964+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask dbt_run
[2024-11-14T17:03:43.966+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=499) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-14T17:03:43.967+0000] {standard_task_runner.py:63} INFO - Started process 500 to run task
[2024-11-14T17:03:44.002+0000] {task_command.py:426} INFO - Running <TaskInstance: Stock_DAG_ELT_dbt.dbt_run manual__2024-11-14T17:03:43.321840+00:00 [running]> on host 214073c88124
[2024-11-14T17:03:44.075+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Stock_DAG_ELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T17:03:43.321840+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T17:03:43.321840+00:00'
[2024-11-14T17:03:44.076+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T17:03:44.089+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T17:03:44.090+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2024-11-14T17:03:44.097+0000] {subprocess.py:86} INFO - Output:
[2024-11-14T17:03:45.908+0000] {subprocess.py:93} INFO - [0m17:03:45  Running with dbt=1.8.7
[2024-11-14T17:03:46.814+0000] {subprocess.py:93} INFO - [0m17:03:46  Registered adapter: snowflake=1.8.4
[2024-11-14T17:03:48.086+0000] {subprocess.py:93} INFO - [0m17:03:48  Encountered an error:
[2024-11-14T17:03:48.087+0000] {subprocess.py:93} INFO - 'dbt_snowflake://macros/metadata.sql'
[2024-11-14T17:03:48.088+0000] {subprocess.py:93} INFO - [0m17:03:48  Traceback (most recent call last):
[2024-11-14T17:03:48.088+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
[2024-11-14T17:03:48.089+0000] {subprocess.py:93} INFO -     result, success = func(*args, **kwargs)
[2024-11-14T17:03:48.089+0000] {subprocess.py:93} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2024-11-14T17:03:48.089+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
[2024-11-14T17:03:48.089+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-14T17:03:48.090+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-14T17:03:48.090+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 218, in wrapper
[2024-11-14T17:03:48.090+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-14T17:03:48.091+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-14T17:03:48.091+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 247, in wrapper
[2024-11-14T17:03:48.091+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-14T17:03:48.092+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-14T17:03:48.092+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 294, in wrapper
[2024-11-14T17:03:48.092+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2024-11-14T17:03:48.092+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2024-11-14T17:03:48.092+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 320, in wrapper
[2024-11-14T17:03:48.093+0000] {subprocess.py:93} INFO -     ctx.obj["manifest"] = parse_manifest(
[2024-11-14T17:03:48.093+0000] {subprocess.py:93} INFO -                           ^^^^^^^^^^^^^^^
[2024-11-14T17:03:48.093+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 1898, in parse_manifest
[2024-11-14T17:03:48.093+0000] {subprocess.py:93} INFO -     manifest = ManifestLoader.get_full_manifest(
[2024-11-14T17:03:48.093+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-11-14T17:03:48.094+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 330, in get_full_manifest
[2024-11-14T17:03:48.094+0000] {subprocess.py:93} INFO -     manifest = loader.load()
[2024-11-14T17:03:48.094+0000] {subprocess.py:93} INFO -                ^^^^^^^^^^^^^
[2024-11-14T17:03:48.094+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 399, in load
[2024-11-14T17:03:48.094+0000] {subprocess.py:93} INFO -     self.load_and_parse_macros(project_parser_files)
[2024-11-14T17:03:48.095+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/parser/manifest.py", line 676, in load_and_parse_macros
[2024-11-14T17:03:48.095+0000] {subprocess.py:93} INFO -     block = FileBlock(self.manifest.files[file_id])
[2024-11-14T17:03:48.095+0000] {subprocess.py:93} INFO -                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
[2024-11-14T17:03:48.095+0000] {subprocess.py:93} INFO - KeyError: 'dbt_snowflake://macros/metadata.sql'
[2024-11-14T17:03:48.095+0000] {subprocess.py:93} INFO - 
[2024-11-14T17:03:48.870+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-14T17:03:48.871+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T17:03:48.880+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-14T17:03:48.883+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Stock_DAG_ELT_dbt, task_id=dbt_run, run_id=manual__2024-11-14T17:03:43.321840+00:00, execution_date=20241114T170343, start_date=20241114T170343, end_date=20241114T170348
[2024-11-14T17:03:48.893+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 77 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 500)
[2024-11-14T17:03:48.917+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T17:03:48.934+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T17:03:48.938+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
